Resource for VN-439
anyTV/freedom-crypto-miner-i18n pull request #22
Opened 2018-10-15 09:32 UTC by votuanphong1983

Resource for ticket VN-439

2018-10-16 04:39 UTC, huy2nhan submitted a review, later dismissed

2018-10-16 04:39 UTC, huy2nhan commented on cs/index.json
> +    "not_support_system": "System can not mine. Maybe RAM is not enough or your preferred algorithms are not suppored. Please check on 'Configure-Preferred Algorithms' menu. Minable algorithms list [
I think saying `preferred algorithms are not suppored` sounds a bit odd, and `cannot` is more usual than `can not`. My suggestion:
```
Device is not supported or out of memory. Please check on 'Configure-Preferred Algorithms' menu. Minable algorithms: [{{algorithms}}]
```

2018-10-16 04:39 UTC, huy2nhan commented on cs/index.json
> +    "validate_fail_out_of_memory": "RAM is not enough. RAM must be at least {{ram}} MB",
RAM can be confused as machine RAM, should use VRAM instead or stats it as `device memory`?. My suggestion:
```
Insufficient device memory. VRAM must be at least {{vram}} MB."
```

2018-10-16 04:39 UTC, huy2nhan commented on cs/index.json
> +    "predict_dag_expire_date": "DAG size of {{crypto}} is {{dagSize}} MB. You RAM({{curRAM}} MB) can mine to {{expireAt}}"
`You RAM({{curRAM}} MB) can mine to {{expireAt}}` is a bit odd and space missing. My suggestion:
```
DAG size of {{crypto}} is {{dagSize}} MB. Your device with {{curRAM}} MB can mine until {{expireAt}}
```

2018-10-16 07:06 UTC, pandafox requested changes
Do we still need these changes?

2018-10-16 07:06 UTC, pandafox commented on zh/index.json
> +    "predict_dag_expire_date": "DAG size of {{crypto}} is {{dagSize}}. You RAM can mine to {{expireAt}}"
```
"validate_fail_out_of_memory": "顯示卡內存不足。VRAM必須至少為{{vram}} MB。",
"validate_fail_unsupported_device": "不支持的硬體設備"，
"predict_dag_expire_date": "{{crypto}}的DAG大小為{{dagSize}} MB。您的顯示卡有({{curRAM}} MB) 可以挖掘到 {{expireAt}}”
```

2018-10-16 07:06 UTC, pandafox commented on cs/index.json
> +    "predict_dag_expire_date": "DAG size of {{crypto}} is {{dagSize}} MB. You RAM({{curRAM}} MB) can mine to {{expireAt}}"
```
    "validate_fail_out_of_memory": "Insufficient Video device memory. VRAM must be at least {{vram}} MB.",
    "validate_fail_unsupported_device": "Unsupported device",
    "predict_dag_expire_date": "DAG size of {{crypto}} is {{dagSize}} MB. Your Video RAM ({{curRAM}} MB) can mine to {{expireAt}}"
```

2018-10-17 06:30 UTC, pandafox approved these changes

2018-10-19 06:29 UTC, merged