VN-517 Improve idle mining logic
anyTV/freedom-crypto-miner-i18n pull request #27
Opened 2018-11-23 03:39 UTC by angels2it

## Ticket references
- [VN-517](https://freedom.myjetbrains.com/youtrack/issue/VN-517)

## Summary of changes

* Add logic to skip idle mining if CPU usage greater than 50%
* Add logic to skip udle mining if has an application in exclusion list is running
* A page to help user config application exclusion list
* Add language for VN-517

## Checklist

- [ ] bugfix
- [x] new feature
- [ ] breaking change
- [ ] added unit tests
- [ ] changes introduced has been discussed and approved
- [ ] requires manual testing
- [ ] documentation has been updated

## Testing

* Enable idle mining

Case 1:
- Select application in config -> to said idle mining does not run while it's running
- Starting selected app
- let computer idle 30s
Expected: miner does not start

Case 2:
- Select application in config -> to said idle mining does not run while it's running
- Stop selected app
- let computer idle 30s
Expected: idle logic trigger start mining action

For CPU case, You may need to update config of CPU_MAX_LOAD to small value for testing or try to burn you CPU usage to > 50 percent :D

2018-11-23 07:44 UTC, pandafox commented on cs/index.json
> +      "reload_hint": "If the application does not has in below list, Try to start it & click refresh icon"
If the application you want to add is not listed, try to start it first and come back and refresh the list.

2018-11-28 02:54 UTC, pandafox commented on cs/index.json
> +      "clear_hint": "Clear all selected applications",
Would this be clear, or remove all selected applications?

2018-11-28 04:55 UTC, pandafox requested changes

2018-11-28 04:55 UTC, pandafox commented on zh/index.json
> +      "running_applications": "Running applications"
```
 "title": "排除應用程序",
      "description": "當下列應用程序運行時，空閒挖掘將不會啟動",
      "filter": "“搜索應用程序",
      "reload_hint": "如果未列出要添加的應用程序，請先嘗試啟動它，然後返回並刷新列表。",
      "select_application_button": "“如果我的應用程序正在運行，不要挖掘",
      "add_hint": "通過從文件對話框中選擇它來添加應用程序",
      "remove_hint": "刪除所有選定的應用程序",
      "selected_applications": "選定的應用程序",
      "running_applications": "正在運行的應用程序"
```

2018-11-28 04:55 UTC, pandafox commented on zh/index.json
> +      "exclusion_confirm_button": "I have added miners folder to my Antivirus software"
shouldn't we replace crypto miner, windows defender with the translation key directly so we can use the same wording?

Additionally, 
```
"exclusion_confirm_button": "I have added miners folder to my Antivirus software's exclusion list."
```

```
      "auto_add_miners_folder_to_exclusion_list_error_title": "採礦工具錯誤排除",
      "auto_add_miners_folder_to_exclusion_list_error_message": "採礦工具文件夾添加到Windows Defender的排除列表時出錯，請單擊下面的按鈕再試一次或嘗​​試重新啟動Crypto Miner",
      "restart_crypto_miner_button": "重啟Crypto Miner",
      "exclusion_confirm_button": "我已將採礦工具文件夾添加到我的防病毒軟件排除列表"
```

2018-11-29 07:13 UTC, angels2it commented on zh/index.json
> +    "checking_windows_defender_config": "Checking Windows Defender configuration",
Please help translate this key

2018-12-03 10:53 UTC, pandafox commented on zh/index.json
> +    "checking_windows_defender_config": "Checking Windows Defender configuration",
```
"checking_windows_defender_config": "正在檢查Windows Defender設定",
```

2018-12-04 05:19 UTC, pandafox approved these changes

2018-12-04 06:53 UTC, merged