Add resources that relate to Wattage (ticket VN-200)
anyTV/freedom-crypto-miner-i18n pull request #8
Opened 2018-04-19 06:12 UTC by votuanphong1983

Ticket [VN-200](https://freedom.myjetbrains.com/youtrack/issue/VN-200)

2018-04-19 07:08 UTC, pandafox requested changes

2018-04-19 07:08 UTC, pandafox commented on zh/index.json
> +    "click_setup_wattage": "Click to setup wattage for more accurate estimation",
Not sure why "click" is in this key, shouldn't this just be setup_wattage?

2018-04-19 07:08 UTC, pandafox commented on zh/index.json
> +    "mining_electricity_consuption": "Mining electricity consumption of your GPUs/CPUs",
mining_electricity_consuption

typo

2018-04-19 07:08 UTC, pandafox commented on zh/index.json
> +    "estimate_again": "Estimate again"
```
    "click_setup_wattage": "設置預估電費",
    "revenue_acronum": "收入",
    "profit_acronum": "利潤",
    "wattage": "瓦數",
    "wattage_cost": "電費",
    "mining_electricity_consuption": "挖掘時的耗電量",
    "electric_cost": "電費 1 kWh",
    "estimate_again": "重新預估"
```

2018-04-20 04:00 UTC, angels2it approved these changes

2018-04-20 04:01 UTC, pandafox approved these changes

2018-04-20 04:03 UTC, merged